import React from 'react';

import {
  Text,
  StyleSheet
} from 'react-native';

function TermsText(){
    return (
    <>
      <Text style={styles.mainTitle}>Terms & Conditions</Text>
      
      <Text style={styles.headerText}>1. ACCEPTANCE OF TERMS</Text>
      <Text style={styles.centerText}>The service that THE DEVELOPERS provide to the user is subject to the following Terms of Use (“TOU”). THE DEVELOPERS reserve the right to update the TOU at any time. The most current version of the TOU can be reviewed by clicking on the “Terms of Use” hypertext link located at the bottom of the Web pages or found inside the Application.</Text>
      <Text style={styles.centerText}>A.	This Agreement, which incorporates by reference other provisions applicable to use of THE DEVELOPERS applications and website services, including, but not limited to, supplemental terms and conditions set forth hereof (“Supplemental Terms”) governing the use of certain material contained in THE DEVELOPERS applications and website services, sets forth the terms of conditions that apply to use of THE DEVELOPERS by its users. By using THE DEVELOPERS (other than to read this Agreement for the first time). The user agrees to comply with all of the terms and conditions hereof. The right to use THE DEVELOPERS applications and website services is personal to the user and is not transferrable to any other person or entity. The user is responsible for all use of the user’s Account (under any screen name or password) and for ensuring that all use of the user’s Account complies fully with the provisions of this Agreement. The user shall be responsible for protecting the confidentiality of the user’s password(s), if any.</Text>
      <Text style={styles.centerText}>B.	THE DEVELOPERS shall have the right at any time to change or discontinue any aspect or feature of THE DEVELOPERS applications and websites, including, but not limited to, content, hours of availability, and equipment needed for access or-use.</Text>

      <Text style={styles.headerText}>2. CHANGED TERMS</Text>
      <Text style={styles.centerText}>THE DEVELOPERS shall have the right at any time to change or modify the terms and conditions applicable to the user’s use of THE DEVELOPERS applications and website services, or any part thereof, or to impose new conditions, including, but not limited to, adding fees charges for use. Such changes, modifications, additions or deletions shall be effective immediately upon notice thereof, which may be given by means including, but not limited to, posting on THE DEVELOPERS applications and website services, or by electronic or conventional mail, or by any other means by which the user obtains notice thereof. Any use of THE DEVELOPERS applications and website services by the user after such notice shall be deemed to constitute acceptance by the user of such changes, modifications or additions.</Text>

      <Text style={styles.headerText}>3. DESCRIPTION OF SERVICE</Text>
      <Text style={styles.centerText}>Through its Web property, THE DEVELOPERS provides the user with access to a variety of resources, including download areas, communication forums and product information (collectively “Services”). The Services, including any updates, enhancements, new features, and/or the addition of any new Web properties, are subject to the TOU.</Text>

      <Text style={styles.headerText}>4. EQUIPMENT</Text>
      <Text style={styles.centerText}>The user shall be responsible for obtaining and maintaining all telephone, computer hardware, software and other equipment needed for access to and use of THE DEVELOPERS applications and website services and all charges related thereto.</Text>

      <Text style={styles.headerText}>5. USER CONDUCT</Text>
      <Text style={styles.centerText}>a.	The user shall use THE DEVELOPERS applications and website services for lawful purposes only. The user shall not post or transmit through THE DEVELOPERS applications and website services any material which violates or infringes in any way upon the rights of others, which is unlawful, threatening, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane or otherwise objectionable, which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law, or which, without THE DEVELOPERS’s express prior approval, contains advertising or any solicitation with respect to products or services. Any conduct by a User that in THE DEVELOPERS’s discretion restricts or inhibits any other User from using or enjoying THE DEVELOPERS applications and website services will not be permitted. The user shall not use THE DEVELOPERS applications and website services to advertise or perform any commercial solicitation, including, but not limited to, the solicitation of the users to become subscribers of other on-line information services competitive with THE DEVELOPERS.</Text>
      <Text style={styles.centerText}>b.	THE DEVELOPERS applications and website services contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music and sound, and the entire contents of THE DEVELOPERS applications and website services are copyrighted. The user may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. The user may download copyrighted material for the user’s personal use only. Except as otherwise expressly permitted under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material will be permitted without the express permission of THE DEVELOPERS and the copyright owner. In the event of any permitted copying, redistribution or publication of copyright notice shall be made. The user acknowledges that it does not acquire any ownership rights by downloading copyrighted material.</Text>
      <Text style={styles.centerText}>c.	The user shall not upload, post or otherwise make available on THE DEVELOPERS applications and website services any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right and the burden of determining that any material is not protected by copyright rests with The user. The user shall be solely liable for any damage resulting from any infringement of copyrights, proprietary rights, or any other harm resulting from such a submission. By submitting material to any public area of THE DEVELOPERS applications and website services, The user automatically grants, or warrants that the owner of such material has expressly granted THE DEVELOPERS the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copy right that may exist in such material. The user also permits any other User to access, view, and store or reproduce the material for that User’s personal use. The user hereby grants THE DEVELOPERS the right to edit, copy, publish and distribute any material made available on THE DEVELOPERS  by the user.</Text>
      <Text style={styles.centerText}>d.	The foregoing provisions of Section 5 are for the benefit of THE DEVELOPERS, its subsidiaries, affiliates and its third party content providers and licensors and each shall have the right to assert and enforce such provisions directly or on its own behalf.</Text>


      <Text style={styles.headerText}>6. USE OF SERVICE</Text>
      <Text style={styles.centerText}>The Services may contain email services, bulletin board services, chat services, chat areas, news groups, forums, communities, personal web pages, applications, calendars, photo albums, file cabinets and/or other message or communication facilities designed to enable The user to communicate with others (each a “Communication Service” and collectively “Communication Services”). The user agrees to use the Communication Services only to post, send and receive messages and material that are proper and, when applicable, related to the particular Communication Service. By way of example, and not as a limitation, the user agrees that when using the Communication Services, The user will not:</Text>
      <Text style={styles.centerText}>	Use the Communication Services in connection with surveys, contests, pyramid schemes, chain letters, junk mail, spamming or any duplicative or unsolicited messages (commercial or otherwise). </Text>
      <Text style={styles.centerText}>	Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</Text>
      <Text style={styles.centerText}>	Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, obscene, indecent or unlawful topic, name, material or information.</Text>
      <Text style={styles.centerText}>	Upload, or otherwise make available, files that contain images, photographs, software or other material protected by intellectual property laws, including, by way of example, and not as limitation, copyright or trademark laws (or by rights of privacy or publicity) unless The user own or control the rights thereto or have received all necessary consent to do the same.</Text>
      <Text style={styles.centerText}>	Use any material or information, including images or photographs, which are made available through the Services in any manner that infringes any copyright, trademark, patent, trade secret, or other proprietary right of any party.</Text>
      <Text style={styles.centerText}>	Upload files that contain viruses, Trojan horses, worms, time bombs, cancel bots, corrupted files, or any other similar software or programs that ma damage the operation of another’s computer or property of another.</Text>
      <Text style={styles.centerText}>	Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Services specifically allows such messages.</Text>
      <Text style={styles.centerText}>	Download any file posted by another user of a Communication Service that the user know, or reasonably should know, cannot be legally reproduced, displayed, performed, and/or distributed in such manner.</Text>
      <Text style={styles.centerText}>	Falsify or delete any copyright management information, such as author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</Text>
      <Text style={styles.centerText}>	Restrict or inhibit any other user from using and enjoying the Communication Services.</Text>
      <Text style={styles.centerText}>	Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service.</Text>
      <Text style={styles.centerText}>	Harvest or otherwise collect information about others, including email addresses.</Text>
      <Text style={styles.centerText}>	Violate any applicable laws or regulations.</Text>
      <Text style={styles.centerText}>	Create a false identity for the purpose of misleading others.</Text>
      <Text style={styles.centerText}>	Use, download or otherwise copy, or provide (whether or not for a fee) to a person or entity any directory of users of the Services or other user or usage information or any portion thereof.</Text>
      <Text style={styles.centerText}>THE DEVELOPERS have no obligation to monitor the Communication Services. However, THE DEVELOPERS reserves the right to review materials posted to the Communication Services and to remove any materials in its sole discretion. THE DEVELOPERS reserves the right to terminate the user’s access to any or all of the Communication Services at any time, without notice, for any reason whatsoever. THE DEVELOPERS reserves the right at all times to disclose any information as it deems necessary to satisfy any applicable law., regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in THE DEVELOPERS’s sole discretion.</Text>
      <Text style={styles.centerText}>Materials uploaded to the Communication Services may be subject information in any Communication Services. THE DEVELOPERS does not control or endorse the content, messages or information found in any Communication Services and, therefore, THE DEVELOPERS specifically disclaims any liability with regard to the Communication Services and any actions resulting from the user’s participation in any Communication Services. Managers and hosts are not authorized THE DEVELOPERS spokespersons, and their views do not necessarily reflect those of THE DEVELOPERS.</Text>

      <Text style={styles.headerText}>7. MEMBER ACCOUNT, PASSWORD, AND SECURITY</Text>
      <Text style={styles.centerText}>If any of the Services requires the user to open an account, the user must complete the registration process by providing THE DEVELOPERS with current, complete and accurate information as prompted by the applicable registration form. The user also will choose a password and a username. The user is entirely responsible for maintaining the confidentiality of the user’s password and account. Furthermore, the user is entirely responsible for any and all activities that occur under the user’s account. The user agrees to notify THE DEVELOPERS immediately of any unauthorized use of the user’s account or any other breach of someone else using the user’s password or account, either with or without the user’s knowledge. However, the user could be held liable for losses incurred by THE DEVELOPERS or another party due to someone else using the user’s account or password. The user may not use anyone else’s account at any time, without the permission of the account holder.</Text>

      <Text style={styles.headerText}>8. NOTICE SPECIFIC TO SOFTWARE AVAILABLE ON THE DEVELOPERS</Text>
      <Text style={styles.centerText}>Any software that is made available to download from the Services (“Software”) is the copyrighted work of THE DEVELOPERS and/or its suppliers. Use of the Software is governed by the terms of the end user license agreement, if any, which accompanies or is included with the Software (“License Agreement”). An end user will be unable to install any Software that is accompanied by or includes a License Agreement, unless he or she first address to the License Agreement terms.</Text>
      <Text style={styles.centerText}>The Software is made available for download solely for use by end users according to the License Agreement. Any reproduction or redistribution of the Software not in accordance with the License Agreement is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible.</Text>
      <Text style={styles.centerText}>WITHOUT LIMITING THE FOREGOING, COPYING OR REPRODUCTION OF THE SOFTWARE TO ANY OTHER SERVER OR LOCATION FOR FURTHER REPRODUCTION OR REDISTRIBUTION IS EXPRESSELY PROHIBITED, UNLESS SUCH REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PERMITTED BY THE LICENSE AGREEMNT ACCOMPANYING SUCH SOFTWARE. THE SOFTARE IS WAARANTED, IF AT ALL, ONLY ACCORING TO THE TERMS OF THE LISENCE AGREEMENT. ECEPT AS WARRANTED IN THE LICENSE AGREEMENT, THE DEVELOPERS HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE SOFTWARE, INCLUDING ALL WARRANTIES AND CONDITIONS OF MERCHANTABILITY, WHETHER EXPRESS, IMPLIED OR STATUTORY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRIGEMENT.</Text>
      <Text style={styles.centerText}>FOR YOUR CONVINIENCE, THE DEVELOPERS MAY MAKE AVAILABLE AS PART OF THE SERVICES OR IN ITS SOFTWARE PRODUCTS, TOOLS AND UTILITIES FOR USE AND/OR DOWNLOAD. THE DEVELOPERS DOES NOT MAKE ANY ASSURANCE WITH REGARD TO THE ACCURACY OF THE RESULTS OR OUTPUT THAT DERIVES FROM SUCH USE OF ANY SUCH TOOLS AND UTILITIES. PLEASE RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS WHEN USING THE TOOLS AND UTILITIES MADE AVAILABLE ON THE SERVICES.</Text>

      <Text style={styles.headerText}>9. NOTICE SPECIFIC TO DOCUMENTS AVAILABLE ON THIS YOUR WEBSITE ADDRESS</Text>
      <Text style={styles.centerText}>Permission to us Documents (such as white papers, press releases, datasheets and FAQs) from the Services is granted, provided that (1) the below copyright notice appears in all copies and that both the copyright notice and this permission notice appear, (2) use of such Documents from the Services is for informational and non-commercial or personal use only and will not be copied or posted on any network computer or broadcast in any media, and (3) no modifications of any Documents are made. Accredited educational institutions, such as universities, private/public colleges, and state community colleges, may download and reproduce the Documents for distribution in the classroom. Distribution outside the classroom requires express written permission. Use for any other purpose is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible.</Text>
      <Text style={styles.centerText}>THE DEVELOPERS AND/OR ITS RESPECTIVE SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE INFORMATION CONTAINED IN THE DOCUMENTS AND RELATED GRAPHICS PUBLISHED AS PART OF THE SERVICES FOR ANY PURPOSE. ALL SUCH DOCUMENTS AND RELATED GRAPHICS ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND. THE DEVELOPERS AND/OR ITS RESPECTIVE SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, INCLUDING ALL WARRANTIES AND CONDITIONS OF MERCHANTABILITY, WHETHER EXPRESS, IMPLIED OR STATUTORY, FITNESS FOR A PARTICULAR PUPOSE, TITLE AND NON-INFRIGEMENT. IN NO EVENT SHALL THE DEVELOPERS AND/OR ITS RESPECTIVE SUPPLIERS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF INFORMATION AVAILABLE FROM THE SERVICES.</Text>
      <Text style={styles.centerText}>THE DOCUMENTS AND RELATED GRAPHICS PULBISHED ON THE SERVICES COULD INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN: THE DEVELOPERS AND’OR ITS RESPECTIVE SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR ITS REPECTIVE SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE PRODUCT(S) AND/OR THE PROGRAM(S) DESCRIBED HEREIN AT ANY TIME.</Text>

      <Text style={styles.headerText}>10. NOTICES REGARDING SOFTWARE, DOCUMENTS AND SERVICES AVAILABLE ON THIS SITE</Text>
      <Text style={styles.centerText}>IN NO EVENT SHALL THE DEVELOPERS AND/OR ITS RESPECTIVE SUPPLIERS BE LIABLE FOR ANY SPECIAL, INIRECT OR CONSEQUENTIALS DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OF PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLEGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF SOFTWARE, DOCUMENTS, PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR INFORMATION AVAILABLE FROM THE SERVICES.</Text>

      <Text style={styles.headerText}>11. MATERIALS PROVIDED TO THE DEVELOPERS OR POSTED AT ANY OF ITS YOUR WEBSITE ADDRESS</Text>
      <Text style={styles.centerText}>THE DEVELOPERS does not claim ownership of the materials The user provide to THE DEVELOPERS (including feedback and suggestions) or post, upload, input or submit to any Services or its associated services for review by the general public, or by the members of any public or private community, (each a “Submission” and collectively “Submissions”). However, by posting, uploading, inputting, providing or submitting (“Posting”) The user’s Submission The user is granted THE DEVELOPERS, its affiliated companies and necessary sublicensees permission to use User’s Submission in connection with the operation of their Internet business (including, without limitation, all THE DEVELOPERS Services), including, without limitation, the license rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat The user’s Submission; to publish The user’s name in connection with The user’s Submission; and the right to sublicense such rights to any supplier of the Services.
  No compensation will be paid with respect to the use of the user’s Submission, as provided herein. THE DEVELOPERS is under no obligation to post or use any Submission The user may provide and THE DEVELOPERS may remove any /submission at any time in its sole discretion. By Posting a Submission as described in these Terms of Use including, without limitation, all the rights necessary for the user to provide, post, upload, input or submit the Submissions.
  </Text>
      <Text style={styles.centerText}>In addition to the warranty and representation set forth above, by Posting a Submission that contain images, photographs, pictures or that are otherwise graphical in whole or in part (“images”), The user warrant and represent that (a) The user is the copyright owner of the images, or that the copyright owner of such images has granted The user permission to use such Images or any content and/or images contained in such images consistent with the manner and purpose of The user’s use and as otherwise permitted by these Terms of Use and the Services, (b) The user have the rights necessary to grant the licenses and sublicenses described in these Terms of Use, and (c) that each person depicted in such Images, if any, has provided consent to the use of the images as set forth in these Terms of Use, including, by way of example, and not as a limitation, the distribution, public display and reproduction of such images. By Posting Images, The user is granting (a) to all members of The user’s private community (for each such images available anywhere on the Services, other than a private community), and/or (b) to the general public (for each such images available anywhere on the Services, other than a private community), permission to use The user’s images in connection with the use, as permitted by these Terms of Use, of any of the Services, (including, by way of example, and not as a limitation, making prints and gift items which include such images), and including, without limitation, a non-exclusive, world-wide, royalty-free license to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat The user’s images without having The user’s name attached to such images, and the right to sublicense such rights to any supplier of the Services. The licenses granted in the preceding sentences for images will ensure the User completely removes such images from the Services, provided that, such termination shall not affect any license granted in connection with such images prior to the time the user completely remove such images. No compensation will be paid with respect to the use of the user’s images.</Text>

      <Text style={styles.headerText}>12. DISCLAIMER OF WARRANTY; LIMITATION OF LIABILITY</Text>
      <Text style={styles.centerText}>a.	THE USER EXPRESSLY AGREES THAT USE OF THE DEVELOPERS  IS AT THE USER’S SOLE RISK. NEITHER THE DEVELOPERS, ITS AFFILIATES NOR ANY OF THEIR RESPECTIVE EMPLOYEES, AGENT, THEIR PARTY CONTENT PROVIDERS OR LICENSORS WARRANT THAT THE DEVELOPERS  WILL BE UNINTERRUPTED OR ERROR FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF http://www.THE DEVELOPERS.com, OR AS TO ACCURACY, RELIABILITY OR CONTENT OF ANY INFORMATION, SERVICE, OR MERCHANDISE PROVIDED THROUGH http://www.THE DEVELOPERS.com.</Text>
      <Text style={styles.centerText}>b.	THE DEVELOPERS  IS PROVIDED ON AN “AS IS” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OTHER THAN THOSE WARRANTIES WHICH ARE IMPLIED BY AND INCAPABLE OF EXCLUSION, RESTRICTION OR MODIFICATION UNDER THE LAWS APPLICABLE TO THIS AGREEMENT.</Text>
      <Text style={styles.centerText}>c.	THIS DISCLAIMER OF LIABILITY APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF RECORD, WHETHER FOR BREACH OF CONTRACT, TORTIOUS BEHAVIOR, NEGLEGENCE, OR UNDER ANY OTHER CAUSE OF ACTION, THE USER SPECIFICALLY ACKNOWLEDGES THAT THE DEVELOPERS IS NOT LIABLE FOR THE DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD-PARTIES AND THAT THE RISK OF INJURY FROM THE FOREGOING RESTS ENTIRELY WITH THE USER.</Text>
      <Text style={styles.centerText}>d.	IN NO EVENT WILL THE DEVELOPERS, OR ANY PERSON OR ENTITY INVOLVED IN CREATING, PRODUCING OR DISTRIBUTING THE DEVELOPERS  OR THE THE DEVELOPERS SOFTWARE, BE LIABLE FOR ANY DAMAGES, INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNATIVE DAMAGES ARISING OUT OF THE USE OF OR INABILITY TO USE http://www.THE DEVELOPERS.com. THE USER HEREBY ACKNOWLEDGES THAT THE PROVISIONS OF THIS SECTION SHALL APPLY TO ALL CONTENT ON THE SITE.</Text>
      <Text style={styles.centerText}>e.	IN ADDITION TO THE TERMS SET FORTH ABOVE NEITHER, THE DEVELOPERS, NOR ITS AFFILIATES, INFORMATION PROVIDERS OR CONTENT PARTNERS SHALL BE LIABLE REGARDLESS OF THE CAUSE OR DURATION, FOR ANY ERRORS, INACCURACIES, OMISSIONS, OR OTHER DEFECTS IN, OR UNTIMELINESS OR UNATHENTICITY OF, THE INFORMATION CONTAINED WITHIN http://www.THE DEVELOPERS.com, OR FOR ANY DELAY OR INTERRUPTION IN THE TRANSMISSION THEREOF TO THE USER, OR FOR ANY CLAIMS OR LOSSES ARISING THEREFROM OR ACCASIONED THEREBY. NONE OF THE FOREGOING PARTIES SHALL BE LIABLE FOR ANY THIRD-PARTY CLAIMS OR LOSSES OF ANY NATURE, INCLUDING, BUT NOT LIMITED TO, LOST PROFITS, PUNATIVE OR CONSEQUENTIAL DAMAGES.</Text>
      <Text style={styles.centerText}>f.	FORCE MAJEURE – NEITHER PARTY WILL BE RESPONSIBLE FOR ANY FAILURE OR DELAY IN PERFORMANCE DUE TO CIRCUMSTANCE BEYOND ITS REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, ACTS OF GOD, WAR, RIOT, EMBARGOES, ACTS OF CIVIL OR MILITARY AUTHORITIES, FIRE, FLOODS, ACCIDENTS, SERVICE OUTAGES RESULTING FROM EQUIPMENT AND/OR SOFTWARE FAILURE AND/OR TELECOMMUNICATIONS FAILURES, POWER FAILURES, NETWORK FAILURES, FAILURES OF THIRD PARTY SERVICE PROVIDERS (INCLUDING PROVIDERS OF INTERNET SERVICES AND TELECOMMUNICATIONS). THE PARTY AFFECTED BY ANY SUCH EVENT SHALL NOTIFY THE OTHER PARTY WITHIN A MAXIMUM OF FIFTEEN (15) DAYS FROM ITS OCCURANCE. THE PERFORMANCE OF THIS AGREEMENT SHALL THEN BE SUSPENDED FOR AS LONG AS ANY SUCH EVENT SHALL PREVENT THE AFFECTED PARTY FROM PERFORMING ITS OBLIGATIONS UNDER THIS AGREEMENT.</Text>

      <Text style={styles.headerText}>13. LINKS TO THIRD PARTY SITES</Text>
      <Text style={styles.centerText}>THE LINKS IN THIS AREA WILL LET YOU LEAVE THE DEVELOPERSS’S SITE. THE LINKED SITES ARE NOT UNDER THE CONTROL OF THE DEVELOPERS AND THE DEVELOPERS IS NOT RESPONSIBLE FOR THE CONTENTS OF ANY LINKED SITE OR ANY LINK CONTAINED IN A LINKED SITE, OR ANY CHANGES OR UPDATES TO SUCH SITES. THE DEVELOPERS IS NOT RESPONSIBLE FOR WEBCASTING OR ANY OTHER FORM OF TRANSMISSION RECEIVED FROM ANY LINKED SITE. THE DEVELOPERS IS PROVDING THESE LINKS TO YOU ONLY AS A CONVINIENCE, AND THE INCLUSION OF ANY LINK DOES NOT IMPLY ENDORESEMENT BY THE DEVELOPERS OF THE SITE.</Text>
      <Text style={styles.centerText}>THE DEVELOPERS is a distributor (and not a publisher) of content supplied by third parties and the users. Accordingly, THE DEVELOPERS has no more editorial control over such content than does a public library, bookstore, or newsstand. Any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, Users or any other user of http://www.THE DEVELOPERS.com, are those of the respective author(s) or distributor(s) and not of THE DEVELOPERS. Neither THE DEVELOPERS nor any third-party provider of information guarantees the accuracy, completeness, or usefulness or any content, nor its merchantability or fitness for any particular purpose.</Text>
      <Text style={styles.centerText}>In many instances, the content available through THE DEVELOPERS  represents the opinions and judgements of the respective information provider, the user, or another user not under contract with THE DEVELOPERS. THE DEVELOPERS neither endorses nor is responsible for the accuracy or reliability of any opinion, advice or statement made on THE DEVELOPERS  by anyone other than authorized THE DEVELOPERS employee spokespersons while for any loss or damage caused by a User’s reliance on information obtained through http://www.THE DEVELOPERS.com. It is the responsibility of the user to evaluate the accuracy, completeness or usefulness of any information, opinion, advice or other content available through THE DEVELOPERS. Please seek the advice of professionals, as appropriate, regarding the evaluation of any specific information, opinion, advice or other content.</Text>

      <Text style={styles.headerText}>14. UNSOLICITED IDEA SUBMISSION POLICY</Text>
      <Text style={styles.centerText}>THE DEVELOPERS OR ANY OF ITS EMPLOYEES DO NOT ACCEPT OR CONSIDER UNSOLICITED IDEAS, INCLUDING IDEAS FOR NEW ADVERTISING, CAMPAIGNS, NEW PROMOTIONS, NEW PRODUCTS OR TECHNOLOGIES, PROCESSES, MATERIAL, MARKETING PLANS OR NEW PRODUCT NAMES. PLEASE DO NOT SEND ANY ORIGINAL CREATIVE ARTWORK, SAMPLES, DEMOS, OR OTHER WORKS. THE SOLE PURPOSE OF THIS POLICY IS TO AVOID POTENTIAL MISUNDERSTANDINGS OR DISPUTES WHEN THE DEVELOPERS’S PRODUCTS OR MARKETING STRATEGIES MIGHT SEEM SIMILAR TO IDEAS TO THE DEVELOPERS OR ANYONE AT THE DEVELOPERS. IF, DESPITE OUR REQUEST THAT YOU NOT SEND US YOUR IDEAS AND MATERIALS, YOU STILL SEND THEM, PLEASE UNDERSTAND THAT THE DEVELOPERS MAKES NO ASSURANCES THAT YOUR IDEAS AND MATERIALS WILL BE TREATED AS CONFIDENTIAL OR PROPRIETARY.</Text>

      <Text style={styles.headerText}>15. MONITORING</Text>
      <Text style={styles.centerText}>THE DEVELOPERS shall have the right, but not the obligation, to monitor the content of THE APPLICATION to determine compliance with this Agreement and any operating rules established by THE DEVELOPERS and to satisfy any law, regulation or authorized government request. THE DEVELOPERS shall have the right in its sole discretion to edit, refuse to post or remove any material submitted to or posted on http://www.THE DEVELOPERS.com. Without limiting the foregoing, THE DEVELOPERS shall have the right to remove any material that THE DEVELOPERS, in its sole discretion, finds to be in violation of the provisions hereof or otherwise objectionable.</Text>

      <Text style={styles.headerText}>16. INDEMNIFICATION</Text>
      <Text style={styles.centerText}>The user agrees to defend, indemnify and hold harmless THE DEVELOPERS, its affiliates and their respective directors, officers, employees and agents from and against all claims and expenses, including attorneys’ fees, arising out of the use of THE DEVELOPERS by the user or User’s Account.</Text>

      <Text style={styles.headerText}>17. TERMINATION</Text>
      <Text style={styles.centerText}>Either THE DEVELOPERS or the User may terminate this Agreement at any time. Without limiting the foregoing, THE DEVELOPERS shall have the right to immediately terminate the user ’s Account in the event of any conduct by the user which THE DEVELOPERS, in its sole discretion, considers to be unacceptable, or in the event of any breach by the user of this Agreement.</Text>

      <Text style={styles.headerText}>18. MISCELLANEOUS</Text>
      <Text style={styles.centerText}>This Agreement and any operating rules for THE DEVELOPERS established by THE DEVELOPERS constitute the entire agreement of the parties with respect to the subject matter hereof, and supersede all previous written or oral agreements between the parties with respect to such subject matter. This Agreement shall be construed in accordance with the laws of the Ontario, Canada, without regard to its conflict of laws rules. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any  preceding or subsequent breach or default. The section headings used herein are convenience only and shall not be given any legal import.</Text>

      <Text style={styles.headerText}>19. COPYRIGHT NOTICE</Text>
      <Text style={styles.centerText}>THE DEVELOPERS logos are trademarks of Canada. All rights reserved. All other trademarks appearing on THE DEVELOPERS are the Property of their respective owners.</Text>

      <Text style={styles.headerText}>20. TRADEMARKS</Text>
      <Text style={styles.centerText}>The names of actual companies and products mentioned herein may be the trademarks of their respective owners. The example companies, organizations, products, domain names, email addresses, logos, people and events depicted herein are fictitious. No association with any real company organization, product, domain name, email address, logo, person, or event is intended or should be inferred.</Text>
      <Text style={styles.centerText}>Any rights no expressly granted herein are reserved.</Text>
    </>
    )
}

const styles = StyleSheet.create({
    centerText: {textAlign: 'justify'},
    headerText: {textAlign: 'center', fontSize: 16, marginVertical: 10},
    mainTitle: {textAlign: 'center', fontSize: 20, marginBottom: 10}
});


export default TermsText