export const MAP_VIEW = 'MAP_VIEW';
export const CORONA_DETAILS = 'CORONA_DETAILS';
export const CORONA_TESTED = 'CORONA_TESTED';

export const COUNTRY_CITY = 'COUNTRY_CITY'

export const COUNTRY_DATA = 'COUNTRY_DATA'
export const CITY_DATA = 'CITY_DATA'
export const WORLD_DATA1 = 'WORLD_DATA1'
export const WORLD_DATA2 = 'WORLD_DATA2'
export const WORLD_DATA3 = 'WORLD_DATA3'
export const WORLD_DATA4 = 'WORLD_DATA4'
export const WORLD_DATA5 = 'WORLD_DATA5'
export const WORLD_DATA30 = 'WORLD_DATA30'
export const WORLD_DATA70 = 'WORLD_DATA70'

export const CITY_BOOKMARK = 'CITY_BOOKMARK'
export const COUNTRY_BOOKMARK = 'COUNTRY_BOOKMARK'

export const RM_CITY_BOOKMARK = 'RM_CITY_BOOKMARK'
export const RM_COUNTRY_BOOKMARK = 'RM_COUNTRY_BOOKMARK'

export const AFFECTED_AREA = 'AFFECTED_AREA';
export const UPDATE_DATE = 'UPDATE_DATE'

export const LOCATION_VISIBLE = 'LOCATION_VISIBLE'
export const NOTIFICATION = 'NOTIFICATION'
